[onert] Fix compilation on Ubuntu 25.10 with GCC 15.2.0
Trying to compile generated tests on Ubuntu 25.10 results in a
compilation error due to name clash between test case namespace
and function from the standard library:

> In file included from ../../../../runtime/tests/nnapi/src/generated/all_generated_V1_2_cts_tests.cpp:182:
> ../../../../runtime/tests/nnapi/src/generated/tests/rsqrt.mod.py.cpp:5:11: error: ‘namespace rsqrt { }’ redeclared as different kind of entity
>     5 | namespace rsqrt {
>       |           ^~~~~
> In file included from /usr/include/features.h:523,
>                  from /usr/include/x86_64-linux-gnu/c++/15/bits/os_defines.h:39,
>                  from /usr/include/x86_64-linux-gnu/c++/15/bits/c++config.h:727,
>                  from /usr/include/c++/15/cstddef:51,
>                  from ../../../../runtime/externals/GTEST-1.15.2/googletest/include/gtest/gtest.h:52,
>                  from ../../../../runtime/tests/nnapi/src/generated/tests/../../TestGenerated.h:21,
>                  from ../../../../runtime/tests/nnapi/src/generated/tests/abs_1D_float_nnfw.mod.py.cpp:3,
>                  from ../../../../runtime/tests/nnapi/src/generated/all_generated_V1_2_cts_tests.cpp:4:
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:206:1: note: previous declaration ‘double rsqrt(double)’

ONE-DCO-1.0-Signed-off-by: Arkadiusz Bokowy <a.bokowy@samsung.com>