[onert] Remove unused tensorinfo function from common module
This commit removes unused and broken tensorinfo() function from the
common Python module.

  >>> import onert
  >>> onert.tensorinfo()
  Traceback (most recent call last):
    File ".../onert/common/basesession.py", line 189, in tensorinfo
      return infer.nnfw_tensorinfo()
             ^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'onert.native.libnnfw_api_pybind.infer' has no attribute 'nnfw_tensorinfo'

Removing this function allows to properly use the native tensorinfo
structure from the onert top level module.

  >>> import onert
  >>> onert.tensorinfo()
  <onert.native.libnnfw_api_pybind.tensorinfo object at 0x7601fe0916f0>

ONE-DCO-1.0-Signed-off-by: Arkadiusz Bokowy <a.bokowy@samsung.com>