[logo-core] Fix a warning when building with clang
This commit fixes a warning emitted by clang for the Phase.h header file

There's a mismatch between the original template declaration and the following
specializations of the PhaseEventInfo class/struct. The changes in this commit
fix the following warning (which causes a build break when compiling in strict)

logo/Phase.h:44:13: error: 'PhaseEventInfo' defined as a class template here but previously declared as a struct template;

ONE-DCO-1.0-Signed-off-by: Tomasz Dołbniak <t.dolbniak@partner.samsung.com>