[infra] Update Protobuf to 3.21.12
This commit updates the Protobuf library to a newer version due to the fixes this version contains.

In particular this version contains a fix for a linker error:
/usr/bin/ld: libtriv2_lib_manifest.a(Manifest.pb.cc.o): in function `google::protobuf::MessageLite::~MessageLite()':
/__w/NPU_Compiler/NPU_Compiler/build/overlay/include/google/protobuf/message_lite.h:171:
undefined reference to `google::protobuf::internal::InternalMetadata::~InternalMetadata()'

ONE-DCO-1.0-Signed-off-by: Tomasz Dołbniak <t.dolbniak@partner.samsung.com>